org: nulltemp
app: serverless
service: serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  memorySize: 512
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
            - "sqs:GetQueueUrl"
          Resource: "arn:aws:sqs:${aws:region}:${aws:accountId}:test-queue"
        - Effect: "Allow"
          Action:
            - "sqs:ListQueues"
          Resource: "arn:aws:sqs:${aws:region}:${aws:accountId}:*"

functions:
  hello:
    handler: src/handler.hello
    events:
      - schedule: cron(0 16 * * ? *)
  queueStarter:
    handler: src/queueStarter.exec
  queueWorker:
    handler: src/queueWorker.exec
    reservedConcurrency: 1
    events:
      - sqs:
          arn: arn:aws:sqs:${aws:region}:${aws:accountId}:${self:resources.Resources.TestQueue.Properties.QueueName}
          batchSize: 1

resources:
  Resources:
    TestQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "test-queue"