org: nulltemp
app: serverless
service: serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  memorySize: 512

functions:
  hello:
    handler: handler.hello
    events:
      - schedule: cron(0 16 * * ? *)